# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0UR6Ro_rZFFLaOf0aPMJ1AAZqVhLd_6
"""

!pip install ucimlrepo

"""# Titre"""



print(car_evaluation.variables)

print(car_evaluation.metadata)

from ucimlrepo import fetch_ucirepo

# fetch dataset
car_evaluation = fetch_ucirepo(id=19)

X = car_evaluation.data.features
y = car_evaluation.data.targets

car_evaluation

# =============================
# Analyse visuelle du dataset Car Evaluation
# =============================

# Import des bibliothèques
from ucimlrepo import fetch_ucirepo
import pandas as pd
import matplotlib.pyplot as plt

# =============================
# Chargement du dataset
# =============================
car_evaluation = fetch_ucirepo(id=19)

# Données
X = car_evaluation.data.features
y = car_evaluation.data.targets

# Fusion des features et de la cible
df = pd.concat([X, y], axis=1)

# =============================
# Informations de base
# =============================
print("\n=== Métadonnées ===")
print(car_evaluation.metadata)

print("\n=== Variables ===")
print(car_evaluation.variables)

print("\n=== Aperçu du jeu de données ===")
print(df.head())

# =============================
# Analyse graphique
# =============================

# 1️⃣ Distribution de la variable cible
plt.figure(figsize=(6, 4))
df['class'].value_counts().plot(kind='bar', color='skyblue', edgecolor='black')
plt.title("Distribution des classes (Acceptabilité de la voiture)")
plt.xlabel("Classe")
plt.ylabel("Nombre d'occurrences")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 2️⃣ Diagrammes à barres pour chaque variable catégorielle
categorical_columns = X.columns

for col in categorical_columns:
    plt.figure(figsize=(6, 4))
    df[col].value_counts().plot(kind='bar', color='salmon', edgecolor='black')
    plt.title(f"Distribution de la variable '{col}'")
    plt.xlabel(col)
    plt.ylabel("Fréquence")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

# 3️⃣ Analyse croisée : sécurité vs classe
plt.figure(figsize=(7, 5))
pd.crosstab(df['safety'], df['class']).plot(kind='bar', figsize=(8,5), colormap='viridis')
plt.title("Relation entre sécurité et acceptabilité")
plt.xlabel("Niveau de sécurité")
plt.ylabel("Nombre de voitures")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 4️⃣ Heatmap des fréquences (ex : safety vs lug_boot)
plt.figure(figsize=(6, 5))
heatmap_data = pd.crosstab(df['safety'], df['lug_boot'])
plt.imshow(heatmap_data, cmap='YlGnBu')
plt.title("Heatmap : Sécurité vs Taille du coffre")
plt.xlabel("Taille du coffre (lug_boot)")
plt.ylabel("Niveau de sécurité")
plt.colorbar(label='Fréquence')
plt.xticks(range(len(heatmap_data.columns)), heatmap_data.columns)
plt.yticks(range(len(heatmap_data.index)), heatmap_data.index)
plt.show()